version: "3.8"

services:
    frontend:
        build:
            context: .
            args:
                NEXT_PUBLIC_API_KEY: ${NEXT_PUBLIC_API_KEY}
                NEXT_PUBLIC_API_AUTH_DOMAIN: ${NEXT_PUBLIC_API_AUTH_DOMAIN}
                NEXT_PUBLIC_API_PROJECT_ID: ${NEXT_PUBLIC_API_PROJECT_ID}
                NEXT_PUBLIC_API_APP_ID: ${NEXT_PUBLIC_API_APP_ID}
                NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
                NEXT_PUBLIC_BASE_SOCKET_URL: ${NEXT_PUBLIC_BASE_SOCKET_URL}
        ports:
            - "3000:3000"
        environment:
            NEXT_PUBLIC_API_KEY: ${NEXT_PUBLIC_API_KEY}
            NEXT_PUBLIC_API_AUTH_DOMAIN: ${NEXT_PUBLIC_API_AUTH_DOMAIN}
            NEXT_PUBLIC_API_PROJECT_ID: ${NEXT_PUBLIC_API_PROJECT_ID}
            NEXT_PUBLIC_API_APP_ID: ${NEXT_PUBLIC_API_APP_ID}
            NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
            NEXT_PUBLIC_BASE_SOCKET_URL: ${NEXT_PUBLIC_BASE_SOCKET_URL}
        env_file:
            - .env
